<form action="<?=$this->url(array("controller"=>"contato","action"=>"update"),null,true)?>" method="post">
   <input type="hidden" name="contato_id" value="<?=$this->contato['contato_id']?>" />
   <table width="100%" cellpadding="3" cellspacing="2">
      <tr>
         <td>Nome:</td>
         <td><input type="text" name="contato_nome" value="<?=$this->contato['contato_nome']?>" /></td>
      </tr>
      <tr>
         <td>Telefone:</td>
         <td><input type="text" name="contato_telefone" value="<?=$this->contato['contato_telefone']?>" /></td>
      </tr>
      <tr>
         <td>E-mail:</td>
         <td><input type="text" name="contato_email" value="<?=$this->contato['contato_email']?>" /></td>
      </tr>
   </table>
   <input type="submit" value="Enviar" />
</form>
